# define context fields?

levels:
    type: linear
    interval: 100

XPs:
    # XP pool is predefined
    - Credits
    - SignInsToday

events:
    Cocreator_SignIn: ~
    Cocreator_GiveFeedback:
        actions:
            - xp:
                  name: XP
                  amount: 10
    Cocreator_Reflect:
        actions:
            - xp:
                  name: XP
                  amount: 10
    Cocreator_BlockCreativityDaily:
        actions:
            - xp:
                  name: XP
                  amount: -5
    Cocreator_AbuseActionDaily:
        actions:
            - xp:
                  name: XP
                  amount: -5
    Cocreator_TryAllFeatures:
        actions:
            - xp:
                  name: XP
                  amount: 10
    Cocreator_Stay3Months:
        actions:
            - xp:
                  name: XP
                  amount: 30
    Chat_SendMessage:
        actions:
            - xp:
                  name: XP
                  amount: 1
    Chat_Send100Characters:
        actions:
            - xp:
                  name: XP
                  amount: 1
    Chat_SignInDaily:
        actions:
            - xp:
                  name: XP
                  amount: 2
    Chat_Stay5MinActive:
        actions:
            - xp:
                  name: XP
                  amount: 1
    Chat_ClickLink:
        actions:
            - xp:
                  name: XP
                  amount: 1
    Chat_CopyMessage:
        actions:
            - xp:
                  name: XP
                  amount: 1
    Chat_DigDeeper:
        actions:
            - xp:
                  name: XP
                  amount: 1
    Chat_AskForRecall:
        actions:
            - xp:
                  name: XP
                  amount: 1
    Chat_StayOnTopic:
        actions:
            - xp:
                  name: XP
                  amount: 1
    PersonalityTest_CompleteTest: ~
    FinancialAnalysis_UploadValidDocs:
        actions:
            - xp:
                  name: XP
                  amount: 2
    FinancialAnalysis_RecurrentUpload:
        actions:
            - xp:
                  name: XP
                  amount: 1
    FinancialAnalysis_CopyContent:
        actions:
            - xp:
                  name: XP
                  amount: 1
    FinancialAnalysis_ImproveMetric:
        actions:
            - xp:
                  name: XP
                  amount: 20
    PlanOfAction_CreatePlanOfAction:
        actions:
            - xp:
                  name: XP
                  amount: 2
    PlanOfAction_RememberDream:
        actions:
            - xp:
                  name: XP
                  amount: 3
    PlanOfAction_DailyRemembrance:
        actions:
            - xp:
                  name: XP
                  amount: 1
    PlanOfAction_CheckOffTask:
        actions:
            - xp:
                  name: XP
                  amount: 1
    PlanOfAction_PerformTaskOnTime:
        actions:
            - xp:
                  name: XP
                  amount: 2
    PlanOfAction_StartOnTimeOrEarlier:
        actions:
            - xp:
                  name: XP
                  amount: 3
    PlanOfAction_FinishEarly:
        actions:
            - xp:
                  name: XP
                  amount: 1
    PlanOfAction_Enjoy:
        actions:
            - xp:
                  name: XP
                  amount: 5
    PlanOfAction_ChangeGoalAfterReflection:
        actions:
            - xp:
                  name: XP
                  amount: 2

achievements:
    achievements:
        DailySignIn:
            requirements:
                - event:
                      name: Cocreator_SignIn
                - xp:
                      name: XP
                      amount: 2

    FullExplorer:
        requirements:
            - event:
                  name: PersonalityTest_CompleteTest
                  amount: 1
            - event:
                  name: Chat_SendMessage
                  amount: 3
            - event:
                  name: FinancialAnalysis_UploadValidDocs
                  amount: 1
            - event:
                  name: PlanOfAction_CreatePlanOfAction
                  amount: 1
        actions:
            - xp:
                  name: XP
                  amount: 50
        maxAwarded: 1
        maxAwardedTotal: 1
        hidden: false
